name: Dependencies Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-dependencies:
    name: Check for Outdated Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        run: npm outdated || true

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Create dependency report
        run: |
          echo "# Dependency Report - $(date)" > dependency-report.md
          echo "" >> dependency-report.md
          echo "## Outdated Dependencies" >> dependency-report.md
          echo '```' >> dependency-report.md
          npm outdated >> dependency-report.md || echo "All dependencies are up to date" >> dependency-report.md
          echo '```' >> dependency-report.md
          echo "" >> dependency-report.md
          echo "## Security Audit" >> dependency-report.md
          echo '```' >> dependency-report.md
          npm audit --json >> dependency-report.md || echo "No security issues found" >> dependency-report.md
          echo '```' >> dependency-report.md

      - name: Upload dependency report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-report
          path: dependency-report.md

  update-dependencies:
    name: Update Dependencies (Manual)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git add package.json package-lock.json
          git commit -m "chore: update dependencies [skip ci]"
          git push
